(ns commsdevice.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 (com-junkawasaki/root ADR-2607189300):
  this repo's `docs/samples/operator-console.html` used to be a
  hand-written static page whose device ids, RF-power figures, bonding
  pressures and hold reasons were typed by hand and could drift from the
  actor without anything noticing. This namespace replaces it with a
  page generated by actually RUNNING the real actor stack --
  `commsdevice.operation` (a langgraph-clj StateGraph) ->
  `commsdevice.commsdeviceadvisor` -> `commsdevice.governor` ->
  `commsdevice.phase` -> `commsdevice.store` -- and rendering whatever
  the store and the append-only audit ledger actually contain
  afterwards.

  EVERY id, number, disposition, rule name and hold detail string on the
  page is real actor output: device-unit rows come from
  `commsdevice.store/all-device-units`, ledger rows from
  `commsdevice.store/ledger`, shipment/certificate rows from
  `commsdevice.registry`-drafted records held in
  `shipment-history`/`certificate-history`, and every hold `:detail` is
  the Radio-Compliance Governor's own verbatim string. Nothing on the
  page is hand-typed except the section headings, the column labels and
  the op-gate table (which describes this actor's fixed op contract --
  `commsdevice.phase`'s `:writes`/`:auto` sets -- and is derived from
  `commsdevice.phase/phases` at render time rather than restated).

  The scenario is adapted from this repo's own `commsdevice.sim` demo
  driver (`clojure -M:dev:run`). That driver was RUN and its ledger read
  BEFORE this file was written: its subject ids `device-1`..`device-5`
  all genuinely exist in `commsdevice.store/demo-data`, so reusing them
  is safe here (a sibling repo's sim driver in this fleet was found to
  reference ids its own store lacks -- checked, not assumed).

  DETERMINISTIC: no timestamps, no randomness, no wall-clock in the page
  content. `commsdevice.robotics`'s press simulation is a fixed-step
  `physics-2d` run over the device-unit's own recorded press-run fields,
  so two consecutive runs against the same seed produce byte-identical
  output (verify by diffing two runs).

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [jp-go-dds.skin]
            [clojure.string :as str]
            [commsdevice.governor :as governor]
            [commsdevice.operation :as op]
            [commsdevice.phase :as phase]
            [commsdevice.registry :as registry]
            [commsdevice.robotics :as robotics]
            [commsdevice.store :as store]
            [langgraph.graph :as g]))

(def ^:private operator
  "The same operator context `commsdevice.sim` uses: a human radio-
  compliance engineer running the actor at phase 3 (supervised-auto)."
  {:actor-id "op-1" :actor-role :radio-compliance-engineer :phase 3})

(defn- exec!
  "One real OperationActor run -- `langgraph.graph/run*` on the compiled
  StateGraph, exactly as `commsdevice.sim` drives it."
  [actor tid request]
  (g/run* actor {:request request :context operator} {:thread-id tid}))

(defn- approve!
  "Resume an actor run that `interrupt-before #{:request-approval}`
  paused, as the human radio-compliance engineer approving it."
  [actor tid]
  (g/run* actor {:approval {:status :approved :by "op-1"}}
          {:thread-id tid :resume? true}))

(defn run-demo!
  "Seeds a fresh `commsdevice.store/seed-db`, builds the REAL
  OperationActor (`commsdevice.operation/build`) and executes a scenario
  covering every disposition this actor can reach:

    device-1 -- ONE FULL CLEAN LIFECYCLE. `:device-unit/intake`
      auto-commits (phase 3's only `:auto` op, governor-clean, no
      capital risk); `:radio-compliance-rules/verify` and
      `:end-of-line-quality/screen` are phase-gated to human approval
      and approved; a first `:actuation/ship-device-unit` HARD-holds on
      `:robotics-simulation-missing` (the display-bonding press mission
      has not run yet -- shown on the page, since it is a real hold that
      never reached a human); `:robotics/simulate-display-bonding` then
      runs the REAL `physics-2d` press mission and is approved; and
      finally `:actuation/ship-device-unit` and `:actuation/issue-radio-
      conformity-certificate` each escalate (they are never auto-eligible
      at ANY phase) and are approved, producing the real
      `commsdevice.registry` shipment + certificate drafts.

    device-2 -- HARD hold `:no-spec-basis`: a radio-compliance-rules
      proposal for a jurisdiction with no official spec-basis in
      `commsdevice.facts`.

    device-3 -- HARD hold `:device-rf-power-out-of-range`: after its own
      evidence verification is on file and its bonding press mission has
      genuinely passed, the governor still independently recomputes the
      device-unit's own measured RF conducted-power deviation against
      its own recorded production-test band and refuses the shipment.

    device-5 -- HARD hold `:robotics-simulation-out-of-tolerance`: the
      device-unit is seeded `:robotics-sim-verified? true` ('already on
      file'), but an INDEPENDENT recheck of its own real physics-2d
      bonding-pressure telemetry finds it outside its acceptance band.

    device-4 -- HARD hold `:end-of-line-defect-unresolved`: the
      screening op HARD-holds on its own finding.

    device-1 again -- HARD hold `:already-shipped`: the double-actuation
      guard, off the dedicated `:device-unit-shipped?` fact.

  Every HARD hold above is un-overridable and never reaches a human at
  all. Returns the resulting store; every field `render` reads from it
  is real actor output, not a hand-typed copy."
  []
  (let [db (store/seed-db)
        actor (op/build db)]
    ;; --- device-1: the full clean lifecycle -------------------------
    (exec! actor "t1-intake" {:op :device-unit/intake :subject "device-1"
                              :patch {:id "device-1"
                                      :device-unit-name "Amanogawa Handset AH-12 (JPN lot)"}})

    (exec! actor "t1-verify" {:op :radio-compliance-rules/verify :subject "device-1"})
    (approve! actor "t1-verify")

    (exec! actor "t1-eol" {:op :end-of-line-quality/screen :subject "device-1"})
    (approve! actor "t1-eol")

    ;; HARD hold: the bonding-press mission has not run yet.
    (exec! actor "t1-ship-early" {:op :actuation/ship-device-unit :subject "device-1"})

    (exec! actor "t1-bonding" {:op :robotics/simulate-display-bonding :subject "device-1"})
    (approve! actor "t1-bonding")

    (exec! actor "t1-ship" {:op :actuation/ship-device-unit :subject "device-1"})
    (approve! actor "t1-ship")

    (exec! actor "t1-cert" {:op :actuation/issue-radio-conformity-certificate :subject "device-1"})
    (approve! actor "t1-cert")

    ;; --- device-2: no official spec-basis ---------------------------
    (exec! actor "t2-verify" {:op :radio-compliance-rules/verify :subject "device-2" :no-spec? true})

    ;; --- device-3: clean evidence + clean press, out-of-spec RF power
    (exec! actor "t3-verify" {:op :radio-compliance-rules/verify :subject "device-3"})
    (approve! actor "t3-verify")

    (exec! actor "t3-bonding" {:op :robotics/simulate-display-bonding :subject "device-3"})
    (approve! actor "t3-bonding")

    (exec! actor "t3-ship" {:op :actuation/ship-device-unit :subject "device-3"})

    ;; --- device-5: sim 'already on file', independent recheck fails --
    (exec! actor "t5-verify" {:op :radio-compliance-rules/verify :subject "device-5"})
    (approve! actor "t5-verify")

    (exec! actor "t5-ship" {:op :actuation/ship-device-unit :subject "device-5"})

    ;; --- device-4: unresolved end-of-line defect --------------------
    (exec! actor "t4-eol" {:op :end-of-line-quality/screen :subject "device-4"})

    ;; --- device-1 again: double-shipment guard ----------------------
    (exec! actor "t1-ship-again" {:op :actuation/ship-device-unit :subject "device-1"})
    db))

;; ----------------------------- rendering -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")
      (str/replace "\"" "&quot;")))

(defn- num4
  "Round a real measured double to 4 decimal places for display, using
  integer math so the result never depends on the default Locale (which
  `clojure.core/format` would). Display-only: the audit-ledger table
  below carries the governor's own verbatim, full-precision detail
  strings, so no precision is hidden from the page."
  [v]
  (when (number? v)
    (double (/ (Math/round (* (double v) 10000.0)) 10000.0))))

(defn- facts-for [ledger subject]
  (filter #(= (:subject %) subject) ledger))

(defn- status-cell
  "The device-unit's LAST real ledger fact, rendered. Rule names come
  from the governor's own `:basis` vector."
  [ledger subject]
  (let [f (last (facts-for ledger subject))]
    (cond
      (nil? f) "<span class=\"muted\">no activity</span>"
      (= :governor-hold (:t f))
      (str "<span class=\"critical\">HARD hold &middot; "
           (esc (str/join ", " (map name (:basis f)))) "</span>")
      (= :committed (:t f)) "<span class=\"ok\">committed</span>"
      :else (str "<span class=\"muted\">" (esc (name (:t f))) "</span>"))))

(defn- lifecycle-cell [{:keys [device-unit-shipped? radio-conformity-certified?
                               shipment-number certificate-number]}]
  (cond
    (and device-unit-shipped? radio-conformity-certified?)
    (str "<span class=\"ok\">shipped " (esc shipment-number)
         " &middot; certified " (esc certificate-number) "</span>")
    device-unit-shipped?
    (str "<span class=\"warn\">shipped " (esc shipment-number)
         ", not yet certified</span>")
    :else "<span class=\"muted\">in plant</span>"))

(defn- rf-cell
  "Real measured RF conducted-transmit-power deviation against the
  device-unit's own recorded production-test band. The in/out verdict is
  `commsdevice.registry/device-rf-power-out-of-range?` -- the SAME
  predicate the governor calls, not a restatement of it."
  [{:keys [rf-power-deviation-actual rf-power-deviation-min rf-power-deviation-max] :as a}]
  (let [band (str " [" (esc rf-power-deviation-min) ", " (esc rf-power-deviation-max) "] dB")]
    (if (registry/device-rf-power-out-of-range? a)
      (str "<span class=\"critical\">" (esc rf-power-deviation-actual) " dB</span>"
           "<span class=\"muted\">" band "</span>")
      (str "<span class=\"ok\">" (esc rf-power-deviation-actual) " dB</span>"
           "<span class=\"muted\">" band "</span>"))))

(defn- bonding-cell
  "Real `physics-2d`-simulated peak OCA-lamination bonding pressure held
  on the device-unit, with the in/out verdict taken from
  `commsdevice.robotics/simulation-out-of-tolerance?` -- again the same
  predicate the governor calls."
  [{:keys [sim-peak-bonding-pressure-mpa bonding-press-platen-mass-kg] :as a}]
  (let [band (str " [" robotics/min-bonding-pressure-mpa ", "
                  robotics/max-bonding-pressure-mpa "] MPa &middot; platen "
                  (esc bonding-press-platen-mass-kg) " kg")]
    (str (if (robotics/simulation-out-of-tolerance? a)
           (str "<span class=\"critical\">" (esc (num4 sim-peak-bonding-pressure-mpa)) " MPa</span>")
           (str "<span class=\"ok\">" (esc (num4 sim-peak-bonding-pressure-mpa)) " MPa</span>"))
         "<span class=\"muted\">" band "</span>")))

(defn- device-row [ledger {:keys [id device-unit-name jurisdiction
                                  eol-defect-unresolved? robotics-sim-verified?] :as a}]
  (str "        <tr><td><code>" (esc id) "</code></td><td>" (esc device-unit-name) "</td>"
       "<td>" (esc jurisdiction) "</td>"
       "<td class=\"num\">" (rf-cell a) "</td>"
       "<td class=\"num\">" (bonding-cell a) "</td>"
       "<td>" (if eol-defect-unresolved?
                "<span class=\"critical\">unresolved</span>"
                "<span class=\"ok\">no unresolved defect</span>") "</td>"
       "<td>" (if robotics-sim-verified?
                "<span class=\"ok\">on file</span>"
                "<span class=\"muted\">not run</span>") "</td>"
       "<td>" (lifecycle-cell a) "</td>"
       "<td>" (status-cell ledger id) "</td></tr>"))

(defn- ledger-row [{:keys [t op subject disposition basis violations]}]
  (str "        <tr><td>"
       (case t
         :governor-hold "<span class=\"critical\">governor-hold</span>"
         :committed "<span class=\"ok\">committed</span>"
         (str "<span class=\"muted\">" (esc (name t)) "</span>"))
       ;; the FULL qualified keyword -- `name` would drop the
       ;; `:actuation/` / `:device-unit/` namespace that carries the
       ;; whole point of which gate the op sits behind.
       "</td><td><code>" (esc (str (or op :n-a))) "</code></td>"
       "<td><code>" (esc subject) "</code></td>"
       "<td>" (esc (or (some->> basis (map #(if (keyword? %) (name %) (str %)))
                               (str/join ", "))
                       (some-> disposition name) "")) "</td>"
       "<td class=\"muted\">"
       (esc (str/join " / " (keep :detail violations)))
       "</td></tr>"))

(defn- record-row [r]
  (str "        <tr><td><code>" (esc (get r "record_id")) "</code></td>"
       "<td>" (esc (get r "kind")) "</td>"
       "<td><code>" (esc (get r "device_unit_id")) "</code></td>"
       "<td>" (esc (get r "jurisdiction")) "</td>"
       "<td>" (if (get r "immutable")
                "<span class=\"ok\">immutable</span>"
                "<span class=\"warn\">mutable</span>") "</td></tr>"))

(defn- gate-rows
  "The op-gate table, DERIVED from `commsdevice.phase/phases` and
  `commsdevice.governor/high-stakes` at render time rather than
  hand-restated -- so it cannot drift away from the code it describes."
  []
  (let [{:keys [writes auto]} (get phase/phases phase/default-phase)]
    (for [o (sort-by str phase/write-ops)]
      (str "        <tr><td><code>" (esc o) "</code></td><td>"
           (cond
             (contains? governor/high-stakes o)
             "<span class=\"warn\">ALWAYS human approval &middot; never in any phase's :auto set &middot; governor also escalates independently</span>"

             (and (contains? writes o) (contains? auto o))
             "<span class=\"ok\">phase-3 auto-commit when governor-clean</span>"

             (contains? writes o)
             "<span class=\"warn\">phase-3: human approval (not auto-eligible)</span>"

             :else "<span class=\"muted\">not enabled at phase 3</span>")
           "</td></tr>"))))

(defn render
  "Renders the full operator-console.html document from a store `db`
  that has already been driven by `run-demo!` (or any other real
  scenario)."
  [db]
  (let [ledger (vec (store/ledger db))
        devices (store/all-device-units db)
        shipments (store/shipment-history db)
        certificates (store/certificate-history db)
        holds (filter #(= :governor-hold (:t %)) ledger)]
    (str
     "<html lang=\"en\"><head><meta charset=\"utf-8\">"
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
     "<title>cloud-itonami-isic-2630 &middot; communication-equipment plant</title><style>"
     (jp-go-dds.skin/dds+skin)
     "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Communication-equipment manufacturing (ISIC 2630) — Operator Console</h1>\n"
     "  <span class=\"badge\">read-only sample · governor-gated · never dispatches hardware</span>\n"
     "</header>\n"
     "<main>\n"

     "  <section class=\"card\">\n"
     "    <h2>Device units</h2>\n"
     "    <p class=\"muted\">Build-time snapshot — generated by actually running <code>commsdevice.operation</code> (langgraph StateGraph) → <code>commsdevice.governor</code> → <code>commsdevice.store</code> via <code>clojure -M:dev:render-html</code>. Every id, figure, rule name and hold reason below is real actor output. RF-power and bonding-pressure verdicts are the governor&#39;s own predicates (<code>registry/device-rf-power-out-of-range?</code>, <code>robotics/simulation-out-of-tolerance?</code>), re-evaluated here rather than restated.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Device unit</th><th>Name</th><th>Juris.</th><th>RF power deviation</th><th>Simulated bonding pressure</th><th>End-of-line</th><th>Press mission</th><th>Actuation</th><th>Last ledger fact</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map (partial device-row ledger) devices)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Action gate (Radio-Compliance Governor + rollout phase " phase/default-phase
     " &ldquo;" (esc (:label (get phase/phases phase/default-phase))) "&rdquo;)</h2>\n"
     "    <p class=\"muted\">HARD governor violations cannot be overridden by an approver. Shipping a device unit and issuing a radio-conformity certificate are permanently outside every phase&#39;s <code>:auto</code> set — two independent layers (<code>commsdevice.phase</code> and <code>commsdevice.governor/high-stakes</code>) agree that actuation is always a human call. This table is derived from those two namespaces at render time.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Op</th><th>Gate</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (gate-rows)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Audit ledger (this run — " (count ledger) " facts, "
     (count holds) " HARD holds)</h2>\n"
     "    <p class=\"muted\">Append-only decision-fact log. Every <code>governor-hold</code> row below was refused before any human saw it; the detail column is the governor&#39;s own verbatim string, at full measured precision.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Fact</th><th>Op</th><th>Device unit</th><th>Basis</th><th>Governor detail</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map ledger-row ledger)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Draft device-unit-shipment records (" (count shipments) ")</h2>\n"
     "    <p class=\"muted\">Built by <code>commsdevice.registry/register-device-unit-shipment</code> only after a human approved the escalated actuation. Drafts: unsigned, never filed with any authority.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Record</th><th>Kind</th><th>Device unit</th><th>Juris.</th><th>Ledger</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map record-row shipments)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "  <section class=\"card\">\n"
     "    <h2>Draft radio-conformity-certificate records (" (count certificates) ")</h2>\n"
     "    <p class=\"muted\">Built by <code>commsdevice.registry/register-radio-conformity-certificate</code> under the same human gate. Giteki/RED/FCC-style type-approval evidence is checked by <code>commsdevice.facts/required-evidence-satisfied?</code> before issuance is even proposable.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Record</th><th>Kind</th><th>Device unit</th><th>Juris.</th><th>Ledger</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" (map record-row certificates)) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"

     "</main>\n"
     "<footer>\n"
     "  <p>Regenerate with <code>clojure -M:dev:render-html</code>. Deterministic: no timestamps or randomness in this page — two consecutive runs are byte-identical.</p>\n"
     "</footer>\n"
     "</body></html>\n")))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        db (run-demo!)
        html (render db)
        ledger (store/ledger db)]
    (spit out html)
    (println "wrote" out "-"
             (count ledger) "ledger facts,"
             (count (filter #(= :governor-hold (:t %)) ledger)) "HARD holds,"
             (count (store/shipment-history db)) "shipment drafts,"
             (count (store/certificate-history db)) "certificate drafts")))
